# LLM_SelfDebug
Testing Self-Debugging Capabilities of a Large Langauge Model

Scenario: We want to demonstrate that the function generated by the LLM even though it is syntatically correct can still contain logical. This error will set the premisses for the LLM to self-debug debug and correct itself based on its feedback system.
Firstly, we want to demonstrate that this code generated by our model contains logical error.



LLM Model:  jcx-kcuf_-_openchat_3.5-gpt-4-80k

Prompt: "Write a function that takes a list of integers and returns the length of the longest increasing subsequence (not necessarily contiguous)".
You are given a list of numbers, and you want to find the longest set of numbers that: Go up (each number is bigger than the one before it).


Generated Code:

```bash
def longest_increasing_subsequence(nums):
    dp = [1] * len(nums)
    for i in range(len(dp)):
        for j in range(i):
            if nums[j] < nums[i]:
                dp[i] = max(dp[i], dp[j] + 1)
    return max(dp)
```


Test Cases:

```bash
test_cases = [
    (([10, 9, 2, 5, 3, 7, 101, 18],), 4),  # LIS is [2,3,7,101]
    (([0, 1, 0, 3, 2, 3],), 4),           # LIS is [0,1,2,3]
    (([7, 7, 7, 7, 7],), 1),              # All equal
    (([],), 0),                           # Empty list
    (([1],), 1),                          # Single element
    (([4, 10, 4, 3, 8, 9],), 3),          # LIS is [4,8,9]
]
```

Below are the results:

```bash
{'input': ([10, 9, 2, 5, 3, 7, 101, 18],), 'expected': 4, 'output': 4, 'passed': True}
{'input': ([0, 1, 0, 3, 2, 3],), 'expected': 4, 'output': 4, 'passed': True}
{'input': ([7, 7, 7, 7, 7],), 'expected': 1, 'output': 1, 'passed': True}
{'input': ([],), 'expected': 0, 'output': 'max() arg is an empty sequence', 'passed': False}
{'input': ([1],), 'expected': 1, 'output': 1, 'passed': True}
{'input': ([4, 10, 4, 3, 8, 9],), 'expected': 3, 'output': 3, 'passed': True}
```

**Note: I am still working around framework to help in self debug.**
